image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

test-backend:
  stage: test
  image: docker/compose:latest
  script:
    - docker-compose -f docker-compose.yml up --build --abort-on-container-exit --exit-code-from test
  only:
    - merge_requests
    - main
