services:


  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book_exchange
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - app-network

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - FLASK_ENV=testing
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/book_exchange_test
      - PYTHONPATH=/app
    command: sh -c "sleep 5 && pytest tests/ -v"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

volumes:
  db-data:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
